version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - siteprotect-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - siteprotect-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/usr/share/nginx/html:ro
    depends_on:
      - backend
    networks:
      - siteprotect-network

networks:
  siteprotect-network:
    driver: bridge
